version: "3.9"

services:
  mysql:
    image: mysql:8.4.0
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_todo_api
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d