// Code generated by MockGen. DO NOT EDIT.
// Source: ./tasks.go

// Package repository is a generated GoMock package.
package repository

import (
	task "api/domain/task"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTasksRepositoryInterface is a mock of TasksRepositoryInterface interface.
type MockTasksRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTasksRepositoryInterfaceMockRecorder
}

// MockTasksRepositoryInterfaceMockRecorder is the mock recorder for MockTasksRepositoryInterface.
type MockTasksRepositoryInterfaceMockRecorder struct {
	mock *MockTasksRepositoryInterface
}

// NewMockTasksRepositoryInterface creates a new mock instance.
func NewMockTasksRepositoryInterface(ctrl *gomock.Controller) *MockTasksRepositoryInterface {
	mock := &MockTasksRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockTasksRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTasksRepositoryInterface) EXPECT() *MockTasksRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTasksRepositoryInterface) CreateTask(ctx context.Context, input task.Task) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, input)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTasksRepositoryInterfaceMockRecorder) CreateTask(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTasksRepositoryInterface)(nil).CreateTask), ctx, input)
}

// GetTasks mocks base method.
func (m *MockTasksRepositoryInterface) GetTasks(ctx context.Context) ([]*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx)
	ret0, _ := ret[0].([]*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockTasksRepositoryInterfaceMockRecorder) GetTasks(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockTasksRepositoryInterface)(nil).GetTasks), ctx)
}

// UpdateTask mocks base method.
func (m *MockTasksRepositoryInterface) UpdateTask(ctx context.Context, input task.Task) (*task.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, input)
	ret0, _ := ret[0].(*task.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTasksRepositoryInterfaceMockRecorder) UpdateTask(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTasksRepositoryInterface)(nil).UpdateTask), ctx, input)
}
