openapi: 3.0.0
info:
  title: Todo App API
  version: 1.0.0
servers:
  - url: localhost:8080
tags:
  - name: task
    description: タスクに関するAPI
paths:
  /tasks:
    get:
      summary: タスク一覧を取得する
      tags:
        - task
      operationId: listTasks
      responses:
        '200':
          description: タスク一覧を返す
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: タスクを作成する
      tags:
        - task
      operationId: createTask
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: タスク名
                description:
                  type: string
                  description: タスクの説明
              required:
                - title
      responses:
        '200':
          description: 作成したタスクのID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tasks/{taskId}:
    get:
      summary: タスク詳細を取得する
      tags:
        - task
      operationId: getTaskDetail
      parameters:
        - name: taskId
          in: path
          description: タスクID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: タスク詳細を返す
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: タスクを更新する
      tags:
        - task
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          description: タスクID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: タスク名
                description:
                  type: string
                  description: タスクの説明
                status:
                  $ref: "#/components/schemas/TaskStatus"
              required:
                - title
                - status
      responses:
        '200':
          description: 更新したタスクを返す
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        default:
          description: エラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        status:
          $ref: "#/components/schemas/TaskStatus"
      required:
        - id
        - title
        - description
        - status
    TaskStatus:
      type: string
      enum:
        - todo
        - inProgress
        - done
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message